export { Hero } from "./components/Hero"
export { HadithBanner } from "./components/HadithBanner"
export { PrayerTimes } from "./components/PrayerTimes"
export { SurahFatihaPlayer as SurahFatihaSection } from "./components/SurahFatihaSection"
export { MosqueActivities } from "./components/MosqueActivities"
// export { MosqueStats } from "./components/MosqueStats"
// export { FinanceProgress } from "./components/FinanceProgress"
// export { CommitteePreview } from "./components/CommitteePreview"
// export { ProjectsPreview } from "./components/ProjectsPreview"
// export { GalleryPreview } from "./components/GalleryPreview"
export { DonationCTA } from "./components/DonationCTA"
export { ContactCTA } from "./components/ContactCTA"

export * from "./types"